import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from 'react';
import {drawScene} from './renderer';
import {editStroke,hitMasks,number} from './masks';
import type {Box,Camera,ImageRecord,Mask,Point,Style,Tool} from './types';
import Icon from './Icon';
import {backingSize,viewportToSource} from './coordinates';

export type CanvasHandle = {fit:()=>void;actual:()=>void;zoom:(factor:number)=>void;getImage:()=>HTMLImageElement|null;getView:()=>Camera&{imageId:string}};
type Props={projectId:string;image:ImageRecord;initialView?:Camera&{imageId:string};reloadKey?:number;onRelink?:()=>void; masks:Mask[];compareMasks:Mask[]|null;compareLabel:string;runLabel:string;style:Style;selected:string[];tool:Tool;brushSize:number;points:Point[];box:Box|null;onPoints:(points:Point[])=>void;onBox:(box:Box|null)=>void;onSelection:(ids:string[])=>void;onEdit:(mask:Mask)=>void;onZoom:(zoom:number)=>void;onHover?:(mask:Mask|null)=>void;};
type Drag={kind:'pan'|'point'|'box'|'movebox'|'resizebox'|'stroke';start:{x:number;y:number};client:{x:number;y:number};camera:Camera;points:Point[];box:Box|null;index?:number;stroke?:{x:number;y:number}[]};

export default forwardRef<CanvasHandle,Props>(function WorkspaceCanvas(props,ref) {
  const host=useRef<HTMLDivElement>(null),canvas=useRef<HTMLCanvasElement>(null),image=useRef<HTMLImageElement|null>(null),drag=useRef<Drag|null>(null);
  const [size,setSize]=useState({w:100,h:100}),[camera,setCamera]=useState<Camera>({x:0,y:0,zoom:1}),[loaded,setLoaded]=useState(false),[imageError,setImageError]=useState(''),[hover,setHover]=useState<string|null>(null),[cursor,setCursor]=useState<{x:number;y:number}|null>(null),[space,setSpace]=useState(false),[draft,setDraft]=useState<{points?:Point[];box?:Box|null;stroke?:{x:number;y:number}[]}>({}),[divider,setDivider]=useState(.5);
  const current=useRef(props);current.current=props;const cameraRef=useRef(camera);cameraRef.current=camera;const sizeRef=useRef(size);sizeRef.current=size;const overlapCycle=useRef({key:'',index:0});
  const fit=()=>{const {w,h}=sizeRef.current;const zoom=Math.max(.01,Math.min((w-80)/props.image.width,(h-80)/props.image.height));setCamera({zoom,x:(w-props.image.width*zoom)/2,y:(h-props.image.height*zoom)/2});};
  const zoomBy=(factor:number,cx=sizeRef.current.w/2,cy=sizeRef.current.h/2)=>setCamera(c=>{const next=Math.max(.01,Math.min(32,c.zoom*factor));return {zoom:next,x:cx-(cx-c.x)*next/c.zoom,y:cy-(cy-c.y)*next/c.zoom};});
  useImperativeHandle(ref,()=>({fit,actual:()=>{const {w,h}=sizeRef.current;setCamera({zoom:1,x:(w-props.image.width)/2,y:(h-props.image.height)/2});},zoom:zoomBy,getImage:()=>image.current,getView:()=>({...cameraRef.current,imageId:props.image.id})}),[props.image]);
  useEffect(()=>{const obs=new ResizeObserver(entries=>{const b=entries[0].contentRect;setSize({w:b.width,h:b.height});});if(host.current)obs.observe(host.current);return()=>obs.disconnect();},[]);
  useEffect(()=>{setLoaded(false);setImageError('');const img=new Image();img.onload=()=>{image.current=img;setLoaded(true);const view=props.initialView;if(view?.imageId===props.image.id&&Number.isFinite(view.zoom)&&view.zoom>=.01&&view.zoom<=32&&Number.isFinite(view.x)&&Number.isFinite(view.y))setCamera(view);else fit();};img.onerror=()=>setImageError('The image could not be loaded. Reconnect the SSD, or relink the exact original file to recover missing image assets.');img.src=`/api/projects/${encodeURIComponent(props.projectId)}/images/${encodeURIComponent(props.image.id)}?reload=${props.reloadKey||0}`;return()=>{img.onload=null;img.onerror=null;image.current=null;};},[props.projectId,props.image.id,props.reloadKey]);
  useEffect(()=>{if(loaded&&size.w>100&&size.h>100&&camera.x===0&&camera.y===0)fit();},[size,loaded]);
  useEffect(()=>props.onZoom(camera.zoom),[camera.zoom]);
  useEffect(()=>{const down=(event:KeyboardEvent)=>{if(event.target instanceof HTMLElement&&event.target.closest('input,textarea,select,[contenteditable="true"]'))return;if(event.code==='Space'){event.preventDefault();setSpace(true);}};const up=(event:KeyboardEvent)=>{if(event.code==='Space')setSpace(false);};const blur=()=>setSpace(false);window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);};},[]);
  useEffect(()=>{const el=host.current;if(!el)return;const wheel=(event:WheelEvent)=>{event.preventDefault();const r=el.getBoundingClientRect();zoomBy(Math.exp(-event.deltaY*.002),event.clientX-r.left,event.clientY-r.top);};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[]);
  useEffect(()=>{
    const el=canvas.current,img=image.current;if(!el||!loaded||!img)return;
    const dpr=window.devicePixelRatio||1;const backing=backingSize(size.w,size.h,dpr);el.width=backing.width;el.height=backing.height;el.style.width=`${size.w}px`;el.style.height=`${size.h}px`;const ctx=el.getContext('2d')!;ctx.scale(dpr,dpr);ctx.clearRect(0,0,size.w,size.h);
    const render=(masks:Mask[],style:Style)=>{ctx.save();ctx.translate(camera.x,camera.y);ctx.scale(camera.zoom,camera.zoom);drawScene(ctx,{image:img,masks,style,scale:camera.zoom,selected:props.selected,hovered:hover});ctx.restore();};
    if(props.style.mode==='comparison'){ctx.save();ctx.beginPath();ctx.rect(0,0,size.w*divider,size.h);ctx.clip();render(props.compareMasks||[],props.compareMasks?{...props.style,mode:'both'}:{...props.style,mode:'original'});ctx.restore();ctx.save();ctx.beginPath();ctx.rect(size.w*divider,0,size.w*(1-divider),size.h);ctx.clip();render(props.masks,{...props.style,mode:'both'});ctx.restore();}else render(props.masks,props.style);
    ctx.save();ctx.translate(camera.x,camera.y);ctx.scale(camera.zoom,camera.zoom);const inverse=1/camera.zoom;
    if(props.style.promptsVisible){const points=draft.points||props.points;points.forEach((p,index)=>{ctx.beginPath();ctx.arc(p.x,p.y,7*inverse,0,Math.PI*2);ctx.fillStyle=p.label?'#1a7058':'#ac4d42';ctx.fill();ctx.lineWidth=1.8*inverse;ctx.strokeStyle='#fff';ctx.stroke();ctx.beginPath();ctx.moveTo(p.x-3*inverse,p.y);ctx.lineTo(p.x+3*inverse,p.y);if(p.label){ctx.moveTo(p.x,p.y-3*inverse);ctx.lineTo(p.x,p.y+3*inverse);}ctx.stroke();});const box=draft.box===undefined?props.box:draft.box;if(box){ctx.strokeStyle='#fff';ctx.lineWidth=1.5*inverse;ctx.setLineDash([6*inverse,4*inverse]);ctx.strokeRect(box[0],box[1],box[2]-box[0],box[3]-box[1]);ctx.setLineDash([]);for(const [x,y]of [[box[0],box[1]],[box[2],box[3]]]){ctx.fillStyle='#185b47';ctx.fillRect(x-4*inverse,y-4*inverse,8*inverse,8*inverse);ctx.strokeRect(x-4*inverse,y-4*inverse,8*inverse,8*inverse);}}}
    if(draft.stroke?.length){ctx.save();ctx.strokeStyle=props.tool==='eraser'?'rgba(255,125,104,.8)':'rgba(138,217,191,.8)';ctx.lineWidth=props.brushSize;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();draft.stroke.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.restore();}
    if(cursor&&(props.tool==='brush'||props.tool==='eraser')){ctx.beginPath();ctx.arc(cursor.x,cursor.y,props.brushSize/2,0,Math.PI*2);ctx.strokeStyle='#16291f';ctx.lineWidth=3*inverse;ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=1*inverse;ctx.stroke();}ctx.restore();
  },[loaded,size,camera,props.masks,props.compareMasks,props.style,props.selected,props.points,props.box,props.brushSize,props.tool,hover,cursor,draft,divider]);
  const point=(event:React.PointerEvent|React.MouseEvent)=>{const rect=host.current!.getBoundingClientRect();return viewportToSource(event.clientX,event.clientY,rect,cameraRef.current);};
  const clamp=(p:{x:number;y:number})=>({x:Math.max(0,Math.min(props.image.width-1,p.x)),y:Math.max(0,Math.min(props.image.height-1,p.y))});
  const down=(event:React.PointerEvent)=>{
    if(event.button===2)return;const p=point(event),inBounds=p.x>=0&&p.y>=0&&p.x<props.image.width&&p.y<props.image.height;host.current?.focus();host.current?.setPointerCapture(event.pointerId);
    const base={start:clamp(p),client:{x:event.clientX,y:event.clientY},camera,points:props.points.map(p=>({...p})),box:props.box};
    if(space||props.tool==='pan'||event.button===1){event.preventDefault();drag.current={...base,kind:'pan'};return;}
    if(!inBounds)return;
    if(['select','positive','negative','box'].includes(props.tool)&&props.style.promptsVisible){const idx=props.points.findIndex(q=>Math.hypot(q.x-p.x,q.y-p.y)<11/camera.zoom);if(idx>=0){drag.current={...base,kind:'point',index:idx};return;}
      if(props.box){const box=props.box;const corner=[[box[0],box[1]],[box[2],box[3]]].findIndex(([x,y])=>Math.hypot(x-p.x,y-p.y)<12/camera.zoom);if(corner>=0){drag.current={...base,kind:'resizebox',index:corner};return;}const pad=7/camera.zoom;if(p.x>=box[0]-pad&&p.x<=box[2]+pad&&p.y>=box[1]-pad&&p.y<=box[3]+pad&&(Math.abs(p.x-box[0])<pad||Math.abs(p.x-box[2])<pad||Math.abs(p.y-box[1])<pad||Math.abs(p.y-box[3])<pad)){drag.current={...base,kind:'movebox'};return;}}
    }
    if(props.tool==='positive'||props.tool==='negative'){props.onPoints([...props.points,{...clamp(p),label:props.tool==='positive'?1:0}]);return;}
    if(props.tool==='box'){drag.current={...base,kind:'box'};setDraft({box:[p.x,p.y,p.x,p.y]});return;}
    if(props.tool==='brush'||props.tool==='eraser'){if(props.selected.length===1){drag.current={...base,kind:'stroke',stroke:[p]};setDraft({stroke:[p]});}return;}
    const hits=hitMasks(props.masks,p.x,p.y,props.image.width,props.image.height),key=hits.map(m=>m.id).join(',');if(event.altKey&&overlapCycle.current.key===key)overlapCycle.current.index++;else overlapCycle.current={key,index:0};const found=hits[overlapCycle.current.index%Math.max(1,hits.length)];if(event.shiftKey&&found)props.onSelection(props.selected.includes(found.id)?props.selected.filter(id=>id!==found.id):[...props.selected,found.id]);else props.onSelection(found?[found.id]:[]);
  };
  const move=(event:React.PointerEvent)=>{const p=point(event),d=drag.current;setCursor(p);if(!d){const hit=hitMasks(props.masks,p.x,p.y,props.image.width,props.image.height)[0]||null;setHover(hit?.id||null);props.onHover?.(hit);return;}if(d.kind==='pan'){setCamera({...d.camera,x:d.camera.x+event.clientX-d.client.x,y:d.camera.y+event.clientY-d.client.y});return;}const safe=clamp(p);if(d.kind==='point'){const points=d.points.map((q,i)=>i===d.index?{...q,...safe}:q);setDraft({points});}if(d.kind==='box')setDraft({box:[Math.min(d.start.x,safe.x),Math.min(d.start.y,safe.y),Math.max(d.start.x,safe.x),Math.max(d.start.y,safe.y)]});if(d.kind==='movebox'&&d.box){const dx=Math.max(-d.box[0],Math.min(props.image.width-d.box[2],safe.x-d.start.x)),dy=Math.max(-d.box[1],Math.min(props.image.height-d.box[3],safe.y-d.start.y));setDraft({box:[d.box[0]+dx,d.box[1]+dy,d.box[2]+dx,d.box[3]+dy]});}if(d.kind==='resizebox'&&d.box){const other=d.index===0?{x:d.box[2],y:d.box[3]}:{x:d.box[0],y:d.box[1]};setDraft({box:[Math.min(other.x,safe.x),Math.min(other.y,safe.y),Math.max(other.x,safe.x),Math.max(other.y,safe.y)]});}if(d.kind==='stroke'){d.stroke!.push(safe);setDraft({stroke:[...d.stroke!]});}};
  const up=()=>{const d=drag.current;if(!d)return;drag.current=null;if(d.kind==='point'&&draft.points)props.onPoints(draft.points);if(['box','movebox','resizebox'].includes(d.kind)&&draft.box&&draft.box[2]-draft.box[0]>=1&&draft.box[3]-draft.box[1]>=1)props.onBox(draft.box);if(d.kind==='stroke'){const mask=props.masks.find(m=>m.id===props.selected[0]);if(mask)props.onEdit(editStroke(mask,props.image.width,props.image.height,d.stroke!,props.brushSize/2,props.tool==='eraser'));}setDraft({});};
  return <div ref={host} className={`canvas-surface tool-${space?'pan':props.tool}`} tabIndex={0} aria-label="Image workspace. Use the labeled toolbar or V for selection, Space for pan, F to fit. Coordinates use source pixels." onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{drag.current=null;setDraft({});}} onPointerLeave={()=>{if(!drag.current){setCursor(null);setHover(null);}}} onContextMenu={event=>{event.preventDefault();const p=point(event),idx=props.points.findIndex(q=>Math.hypot(q.x-p.x,q.y-p.y)<12/camera.zoom);if(idx>=0)props.onPoints(props.points.filter((_,i)=>i!==idx));}}>
    <canvas ref={canvas} aria-hidden="true"/>
    {!loaded&&<div className="canvas-message">{imageError?<><Icon name="warning"/><p>{imageError}</p><button className="button" onClick={props.onRelink} onPointerDown={e=>e.stopPropagation()}>Relink original image</button></>:<><span className="spinner"/><p>Loading canonical image…</p></>}</div>}
    {props.style.mode==='comparison'&&loaded&&<><div className="compare-label left">{props.compareLabel}</div><div className="compare-label right">{props.runLabel}</div><div className="comparison-line" style={{left:`${divider*100}%`}}><span><Icon name="compare"/></span></div><input className="comparison-slider" aria-label="Before and after divider" type="range" min="5" max="95" value={divider*100} onChange={e=>setDivider(Number(e.target.value)/100)} onPointerDown={e=>e.stopPropagation()} onPointerMove={e=>e.stopPropagation()}/></>}
    {cursor&&<div className="pixel-coordinate">x {Math.max(0,Math.min(props.image.width-1,Math.floor(cursor.x)))} <span>·</span> y {Math.max(0,Math.min(props.image.height-1,Math.floor(cursor.y)))}</div>}
    {hover&&<div className="hover-chip"><Icon name="layers" size={13}/>{props.masks.find(m=>m.id===hover)?.label||'Unlabeled'}<span>{number(props.masks.find(m=>m.id===hover)?.area||0)} px</span></div>}
  </div>;
});
